### ISSUE TITLE
Issues converting CHANGELOG.rst and AUTHORS.rst to md

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffoldext-markdown#1]
As a next step it makes sense to have at least all text files in the root of a repository as markdown files. These root files like CHANGELOG.rst and AUTHROS.rst are also imported in the Sphinx documentation to avoid double bookkeeping. The problem is now how to include files which are not beneath the docs folder. The current way is to have dummy rst files that use rst's `.. include` statement. This does not work for rst files that include md files. The alternative is to have dummy md files that use Structify's `eval_rst` to call `.. include` from an md file and include the actual md file from the root. This works in theory but breaks right now with a [docutils error](https://github.com/docutils-mirror/docutils/issues/13) which is not yet fixed.

**Comment by raabf** [comment]
I am also interested for generating `CHANGELOG.md` and `AUTHROS.md` !

I currently use another approch and just directly include the md files. For example `docs/authors.rst`:

    .. _authors:
    .. include:: ../AUTHORS.md

and `AUTHORS.md` for example:

    Contributors
    ============
   
    * Fabian Raab <fabian@raab.link>

yes usually they cannot read md files, but it works with the correct extension which adds support for markdown. It is called `recommonmark`. So what has to be done:

  + document requirement `pip install recommonmark`
  + change `../AUTHORS.rst` to `../AUTHORS.md` (and `CHANGELOG.md`)
  + activate the plugin in `docs/conf.py`: `extensions = ['recommonmark']`

Works quite well for me.

**Comment by FlorianWilhelm** [comment]
@raabf, thanks for this hint! I am right now in the progress of preparing a PyScaffold 3.2 release with the necessary updates of the extensions and will include this when I am at it. Thanks!

**Comment by FlorianWilhelm** [comment]
@raabf I finally had some time to test your method. It works for me but the problem still is that in your `AUTHORS.md` you still have RST format and this is why it works. If you change for instance
```
Contributors
============
```
which is RST to MD format
```
# Contributors
``` 
and regenerate the docs you'll see a lot of errors. Can you confirm this or maybe I am doing something wrong here?

**Comment by raabf** [comment]
Oh no :fearful: sorry! you are right! I actually do not get errors during generation, but Markdown only syntax does indeed not render in html output. Then I used by chance only syntax which have Markdown and RST in common and didn't notice that rocommonmark did not render that part. Mhmm well very sad, that this means there is still not solution out there to have md files :disappointed: (Except you see it as solution to only use syntax both markup languge have 😏)

**Comment by FlorianWilhelm** [comment]
I think relying on the fact that there is an intersection of the syntax of MD and RST would be very confusing. If a file has an md ending I would expect it to support all MD syntax. So I guess we have to wait for a better solution.

**Comment by raabf** [comment]
Oh yes of course. The last sentence in brackets war more meant to be a joke 😉. And yes we have to wait  for the bug fix …

**Comment by FlorianWilhelm** [comment]
Awesome! Thanks, @abravalheri for solving this long-standing issue!
