### ISSUE TITLE
Upload sdist to PyPI

### ISSUE THREAD

**Issue by jayvdb** [pyscaffold/pyscaffoldext-markdown#4]
Currently there are only wheels on PyPI.

Please consider uploading sdist with tests to PyPI as part of the release process for future releases, so that they can be used by distro packagers.

Also for https://github.com/pyscaffold/pyscaffoldext-dsproject

**Comment by FlorianWilhelm** [comment]
@jayvdb Sure, thanks for letting me know, I will change this with the next bugfix release.

**Comment by FlorianWilhelm** [comment]
@jayvdb Just for me to understand better, why are source packages better compared to wheels in case of Python-only packages? I just want to understand the process.

**Comment by jayvdb** [comment]
Source packages contain extra bits, especially useful are the tests.
Also wheels depend on pip, while sdist depend on setuptools.  The latter is a build tool, and pip still has some bugs that only relate to packaging, such as reliable timestamps on the files created and other things related to "reproducible builds"

**Comment by FlorianWilhelm** [comment]
I uploaded the current versions as sdists. This will be automatically done with the next release.
