### ISSUE TITLE
docs/requirements.txt gets stripped down to minimum

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffoldext-markdown#8]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
putup --markdown my_project
```

Now running `cat docs/requirements.txt`:
```
recommonmark
```

but expected would be:
```
# Requirements file for ReadTheDocs, check .readthedocs.yml.
# To build the module reference correctly, make sure every external package
# under `install_requires` in `setup.cfg` is also listed here!
recommonmark
sphinx>=3.2.1
# sphinx_rtd_theme
```

**Please provide any additional information below.**

## Versions and main components

* PyScaffold Version: PyScaffold 4.0b2.post26+gb6b8c9e
* Python Version: 3.8
* Operating system: MacOS
* How did you install PyScaffold: pip

**Comment by abravalheri** [comment]
Sorry @FlorianWilhelm, I could not reproduce the bug. Maybe it is because I haven't published the latest version to PyPI?

From master, I can execute:

```bash
% putup --markdown --no-config /tmp/myproj
done! 🐍 🌟 ✨

% cat /tmp/myproj/docs/requirements.txt
# Requirements file for ReadTheDocs, check .readthedocs.yml.
# To build the module reference correctly, make sure every external package
# under `install_requires` in `setup.cfg` is also listed here!
# sphinx_rtd_theme
recommonmark
sphinx>=3.2.1
``` 

I will release a tag right now to see if that was the problem

**Comment by FlorianWilhelm** [comment]
My bad @abravalheri, it seems I wasn't on the last commit. It works perfectly :-)
